[build]
packages = [
    "pyroll" # place your package in the pyroll namespace
]

[version]
path = "pyroll/ring_model.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
    "pyroll-report ~= 2.0",
]

[envs.docs]
path = ""
dependencies = [
    "matplotlib",
    "pygments ~= 2.0",
    "pytask ~= 0.2.0",
    "pytask_latex ~= 0.2.0",
    "jinja2 ~= 3.0.0",
    "toml"
]

[envs.docs.scripts]
build = "pytask" # compile LaTeX docs with latexmk

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]